- .github/workflows/sas_rotation_backups.yml
The preprod AWS environment needs to use the Azure prod storage account.  Fixed this plus added dev and test
> Fix sastoken refresh

- .github/workflows/database_refresh.yml
use CNOMT1 for now as a test DB, test passing control file info to separate job
> DSOS-2483: pull control file info

- .github/workflows/sas_rotation_backups.yml
sas rotation add oasys and csr
> sas rotation add oasys and csr

- .github/workflows/oasys_database_refresh.yml
Just copied nomis pipeline as a placeholder
I'll then test further changes in a branch for a second PR shortly
> DSOS-2668: Add placeholder oasys db refresh pipeline

- patches/redhat.yaml
- Test yaml for testing manual patching via ssm commands
> Test patches for testing emergency patching

- .github/workflows/github_workflow_monitoring.yml
- Update workflow to run on a schedule
> DSOS-2694: update workflow

- .github/workflows/oasys_database_refresh.yml
Removed pp-oasys-db-b refresh schedule
> Removed pp-oasys-db-b refresh schedule

- .github/workflows/github_workflow_monitoring.yml
- add two more repos
- increase the frequency to every 5 mins
> DSOS-2761: add two more repos, increase the frequency to build up a bit of data

- .github/workflows/github_workflow_monitoring.yml
add an additional metric for the total count of failed workflow runs across all repos
> DSOS-2761: add additional metric, without dimension

- .github/workflows/github_workflow_monitoring.yml
> DSOS-2761: use the 0/1 to increment

- .github/workflows/github_workflow_monitoring.yml
- hopefully to make the metric accounting a bit more durable by transmitting it with a timestamp
> DSOS-2761: add a timestamp

- .github/workflows/github_workflow_monitoring.yml
- use the output from the right job
> DSOS-2761: get the right timestamp

- .github/workflows/github_workflow_monitoring.yml
- use the right number in the right position
> DSOS-2761: get the right timestamp, pt II

- .github/workflows/ami_cleanup.yml
Pipeline for ami cleanup. Doesn't do anything yet.
> DSOS-2872: initial pipeline for ami cleanup

- .github/workflows/ami_cleanup.yml
- .github/workflows/snapshot_cleanup.yml
- src/DSO_APPLICATIONS.txt
- src/ami_cleanup.sh
- src/get_dso_aws_accounts.sh
- src/snapshot_cleanup.sh
Add AMI and snapshot cleanup pipelines
> Nomis: DSOS-2872: ami cleanup pipeline

- .github/workflows/nomis_environment_start.yml
- src/nomis/get_nomis_environment.sh
- src/run_script_on_ec2.sh
Initial try at pipeline for bringing nomis environments in and out of service via load balancer
> DSOS-1988: pipeline for starting nomis environments

- .github/workflows/nomis_environment_start.yml
- .github/workflows/nomis_environment_stop.yml
- src/nomis/get_nomis_environment.sh
- src/nomis/nomis_control.sh
Add pipeline for starting and stopping weblogic servers nicely, i.e. also update load balancer to include a healthy message.
Plan is for T1/lsast to be started on-demand using these pipelines
> Nomis: DSOS-1988: environment start pipeline

- .github/workflows/nomis_environment_start.yml
- .github/workflows/nomis_environment_stop.yml
- src/nomis/nomis_control.sh
Tweaks:
- bug fix for Stop pipeline
- remove unnecessary debug
- remove prod from the option list
> Nomis: DSOS-1988: environment start pipeline v3

- .github/workflows/nomis_environment_start.yml
- .github/workflows/nomis_environment_stop.yml
Fix for the scheduled start/stop
> nomis: DSOS-1988: environment start pipeline fix

- .github/workflows/nomis_environment_start.yml
- .github/workflows/nomis_environment_stop.yml
Remove dryrun options and fix bug in stop script
> nomis: DSOS-1988: enable preprod and T3 shutdown out of hours

- .github/workflows/azure_sas_token_refresh.yml
New pipeline for SAS token refresh, intended for use by NDH. Just an initial skeleton.
> DSOS-2803: azure sas token refresh pipeline skeleton

- src/nomis/nomis_control.sh
Still had a bit of debug in there which shouldn't have been there.
> nomis: Fix nomis_control disable maintenance mode

- .github/workflows/azure_sas_token_refresh.yml
- .github/workflows/nomis_environment_start.yml
- .github/workflows/nomis_environment_stop.yml
Simplified the pipeline 
- reduced number of separate jobs to 2
- use matrix functionality
- increase start timeout to 55
> DSOS-2899: nomis pipeline improvements

- .github/workflows/ndh_offloc_cdecopy.yml
- src/run_script_on_ec2.sh
> ndh: DSOS-2895: cdecopy pipeline v2

- .github/workflows/ndh_offloc_cdecopy.yml
- .github/workflows/nomis_environment_start.yml
- .github/workflows/nomis_environment_stop.yml
Fixes to pipeline:
- skip matrix section if the matrix is empty
- add correct parameters to cdecopy script
- run environment start at 9:30 as well in case of any issues the first time around
> ndh: DSOS-2895: cdecopy pipeline v3

- .github/workflows/ndh_offloc_cdecopy.yml
- src/run_script_on_ec2.sh
Just improve the pipeline output so it's clearer what has happened
> ndh: DSOS-2895: cdecopy pipeline v4

- .github/workflows/ndh_offloc_cdecopy.yml
Don't bother copying to PINS as it has been decommissioned
> ndh: DSOS: remove PINS cdecopy

- .github/workflows/aws_ssm_command_invocation_monitoring.yml
- get failed command invocations for two accounts
- update a counter and publish in oem environment account
> DSOS-2925: first pass for a counter to monitor failed command invocation runs

- .github/workflows/aws_ssm_command_invocation_monitoring.yml
- add remaining 'DSO' accounts to be monitored
- add all environments
> DSOS-2925: add all 'dso' accounts

- .github/workflows/github_workflow_monitoring.yml
this can probably be re-factored into one workflow eventually. for now just catch the error from the command if there is one
> BAU: mirroring the style in the SSM monitoring workflow

- .github/workflows/aws_ssm_command_invocation_monitoring.yml
- .github/workflows/github_workflow_monitoring.yml
- add 'dso-modernisation-platform-automation' to the monitoring list
- remove the push rule, run the workflow on schedule only from now on
> BAU: add repo and remove push rule

- .github/workflows/certificate_renewal.yml
Initial pipeline for cert renewal which does nothing so I can test stuff.  There will be subsequence PR for actual implementation
> DSOS-2927: placeholder pipeline for cert renewal

- src/certificates/certs.json
Update PlanetFM training LetsEncrypt cert
> TM-151: Add cafmtrainweb.az.justice.gov.uk as SAN to certs

- src/certificates/certs.json
> TM-151: Add cafmwebx2.az.justice.gov.uk to PlanetFM cert

- .github/workflows/ami_cleanup.yml
- src/ami_cleanup.sh
Improvements to AMI cleanup script to make it easier to see what AMIs will be deleted with dryrun mode.
Outputs list of commands to an artifact which can be viewed / run manually if required.
> TM-451: ami cleanup improvements

- .github/workflows/nomis_combined_reporting_control.yml
- get a list of instances to operate on
- order the list
- simulate the operations with an echo
> TM-405: initial pass at getting a list of non-DB instances to operate on

- .github/workflows/nomis_combined_reporting_control.yml
- add real aws cli commands to control instances
- correct array position for EC2 status
> TM-405: add in aws cli commands to stop/start instances

- .github/workflows/ssm_command_monitoring.yml
Fix typos , remembered this is GHA rather than ansible. So if rather than when.
> TM-679: fix typos in ssm monitoring pipeline

- .github/workflows/github_workflow_monitoring.yml
- .github/workflows/ssm_command_monitoring.yml
- src/github-workflow-monitoring/github-workflow-monitor.py
- src/github-workflow-monitoring/github-workflow-monitor.sh
Reworked pipeline:
- Just run once an hour
- Doesn't duplicate count failures
- Includes a metric for successful pipelines
- Allow workflow dispatch for testing
> TM-718: GitHub monitoring improvements

- src/ssm-command-monitoring/ssm-command-monitor.py
- src/ssm-command-monitoring/ssm-command-monitor.sh
Couple of tiny bug fixes for SSM command monitoring
> TM-679: ssm run command monitor fixes

- .github/workflows/github_workflow_monitoring.yml
- src/github-workflow-monitoring/github-workflow-monitor.py
Fix typo.
Tweak timestamp of metrics to improve display in cloudwatch
> TM-781: GitHub monitoring improvements v2

- .github/workflows/windows_connection_test.yml
> Tm/tm 795/onr poc

- .github/workflows/ncr_environment_start.yml
- .github/workflows/ncr_environment_stop.yml
- src/nomis-combined-reporting/ncr_control.sh
Add preprod to the schedule
Plus some minor fixes
> TM-680: ncr pipeline v2

- .github/workflows/ncr_environment_start.yml
- .github/workflows/ncr_environment_stop.yml
- src/nomis-combined-reporting/ncr_control.sh
Add nomis reporting prod to the pipeline
Some of the stages were timing out so made this a bit more configurable + doubled the timeouts.
> TM-944: add ncr prod

- .github/workflows/ncr_environment_stop.yml
Add environment to the stop job so an authorisation step is required as per NART request.
No authorisation is required for scheduled tasks or dryruns
> TM-1228: ncr: add auth step to pipeline

- .github/workflows/ncr_environment_stop.yml
Improved code for nomis reporting stop pipeline. 
- remove duplicate code and instead use a different github environment name if a reviewer is not required
- validated in test environment
> TM-1228: ncr pipeline auth tweaks

- .github/workflows/ad_clean_computers.yml
Initial upload of new yml file to allow for testing on the branch
> tm-1036-clean-ad-computers-pipeline

- .github/workflows/snapshot_cleanup.yml
This includes the changes to checkout and configure-aws-credentials.
It is to amend the code so it will only allow the use of dryrun and not allow the use of any other option. The code was amended to remove the options section 
dryrun:
type: choice
description: Dryrun mode (leave as false unless testing)
default: false
options:
- true
- false
so it will only allow false to be in place. Too much was originally removed and this was added back (including a missing code piece) and a minor change to set the correct dryrun value.
Details are shown in the comments below.
> Initial version for testing - includes correct actions

- .github/workflows/planetfm_gfsl_data_extract.yml
Initial version of pipeline to allow testing
> TM-1265: planetfm GFSL pipeline initial version

- .github/workflows/planetfm_gfsl_data_extract.yml
- src/planetfm/Add-GFSLDataExtract.ps1
Updates:
- added schedule + invocation of script to pipeline
- committed the powershell script which actually does the upload
> TM-1265: planetfm gsfl upload v2

- .github/workflows/ad_clean_computers.yml
- src/ad_clean_computers.ps1
- src/ad_verify_computers.ps1
Adding AD clean computers scripts.
> TM-1036: clean ad computers pipeline

- .github/workflows/ssm_command_monitoring.yml
This pipeline fails from time to time even if it succeeds on retry. Fixing bug
> TM: ssm command monitoring pipeline bug fix

- .github/workflows/cloudwatch_log_group_cleanup.yml
Manually triggered pipeline to clean up cloudwatch log groups for a given pattern.
> TM-1638: clean patch manager log groups pipeline
